### ISSUE TITLE
Possible bug with data-forwarding deactivated

### ISSUE THREAD

**Issue by smarco** [Mariotti94/WebRISC-V#15]
The following code writes different results on memory depending on data-forwarding activated/deactivated. I would appreciate it if you could have a look at it.

.data
Vector: .word 0,0
.text
la t0, Vector
addi t1, x0, 123
addi t2, x0, 234
nop
addi t0, t0, 4
beq t1, t2, fin
sw t2, 0(t0)
sw t1, -4(t0)
fin:

**Comment by Mariotti94** [comment]
Thank you for bringing this bug to my attention, i will look into it further over the next few days.

**Comment by Mariotti94** [comment]
Hello, i have fixed this bug, the problem was a check in the Hazard Detection Unit that was miswritten.
Thanks again for the report, let me know if you find anything else weird.

PS: The live site is not yet updated, should be updated by tomorrow (you can easily check through the version number, top left under logo).
EDIT: Site updated.

**Comment by smarco** [comment]
Thanks so much for the quick reply and fix. 
I really appreciate it.
