### ISSUE TITLE
JAL instruction in program edit window gives error "label does not exist"

### ISSUE THREAD

**Issue by pxmonti** [Mariotti94/WebRISC-V#21]
When editing a simple program in the edit window I could notice that I cannot use the JAL instruction with a label or with an offset.

REPRO:

jal x1, loop
addi x0,x0,0
loop:
addi t0,t1,5

error shown:
ERROR:
Label does not exist: x1, loop

Expected behavior:
The program correctly compiles the assembly with the offset for the JAL instruction.

**Comment by Mariotti94** [comment]
Hello, this bug is now fixed.
It was an error in the jal instruction parser: the register was hardcoded as in the pseudo jal, so the instruction expected only the label (e.g. jal loop); now it recognizes both the normal and the pseudo jal.
Thanks for the report, let me know if you find anything else weird.

**Comment by pxmonti** [comment]
Thank you for the quick feedback. Yes, in the end I took a look at the code and figured out myself what the problem was and changed my code to something like "jal loop". Good to know that now it works with both syntaxes.
Kind regards
